name: gaitutils-dev
channels:
  - conda-forge
dependencies:
  - configobj
  - flask
  - matplotlib
  - numpy
  - scipy
  - python=3.11 # Required by viconnexusapi
  - openpyxl
  - pip
  - plotly
  - pyqt
  - psutil
  - werkzeug
  - pypdf2
  - dash
  - python-kaleido
  - dash-daq
  - pyedflib
  - ezc3d
  # development-specific
  - ipykernel
  - pip:
  #  - https://github.com/NCH-Motion-Laboratory/gaitutils/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/ulstools/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/configdot/archive/master.zip