name: gaitutils
channels:
  - defaults
dependencies:
  - configobj
  - flask
  - freetype
  - future
  - matplotlib
  - numpy
  - scipy
  - python=2.7
  - openpyxl
  - plotly
  - pyqt
  - spyder
  - jupyter
  - urllib3
  - werkzeug
  - xlrd
  - xlsxwriter
  - xlutils
  - pip:
    - dash
    - dash-daq
    - flake8
    - pytest
    - pathlib
    # use pip editable mode solely to get py style console_scripts
    # (i.e. gaitmenu-script.py) in the environment script dir;
    # these are needed to run the entry points in the given environment
    # via a desktop shortcut etc. pip by default will install exe style
    # console scripts only
    - -e git+https://github.com/jjnurminen/gaitutils.git#egg=gaitutils
    - https://github.com/jjnurminen/ulstools/archive/master.zip

