name: gaitutils
channels:
  - conda-forge
dependencies:
  - configobj=5.0.9
  - flask=3.1.3
  - matplotlib=3.11.1
  - numpy=2.4.6
  - scipy=1.17.1
  - python=3.11.14  # Required to run on HUS computers, other (higher?) versions might cause problems. Also vrsion 3.11 is required by Nexus API.
  - openpyxl=3.1.5
  - pip=26.2.1
  - plotly=6.9.0
  - pyqt=5.15.11
  - psutil=7.2.2
  - werkzeug=3.1.8
  - pypdf2=3.0.1
  - dash=4.4.1
  - python-kaleido=1.3.0
  - dash-daq=0.6.0
  - pyedflib=0.1.42
  - ezc3d=1.7.2
  - pip:
    - https://github.com/NCH-Motion-Laboratory/gaitutils/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/ulstools/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/configdot/archive/master.zip