name: gaitutils
channels:
  - defaults
dependencies:
  - configobj
  - flask
  - freetype
  - future
  - matplotlib
  - numpy
  - scipy
  - python=2.7
  - openpyxl
  - pip
  - plotly
  - pyqt
  - spyder
  - jupyter
  - urllib3
  - werkzeug
  - xlrd
  - xlsxwriter
  - xlutils
  - pip:
    - brotli==1.0.7
    - dash
    - dash-daq
    - flake8
    - pytest
    - pathlib
    - https://github.com/jjnurminen/gaitutils/archive/master.zip
    - https://github.com/jjnurminen/ulstools/archive/master.zip

