name: gaitutils
channels:
  - defaults
dependencies:
  - configobj
  - flask
  - freetype
  - future
  - matplotlib
  - numpy
  - scipy
  - python=2.7
  - openpyxl
  - plotly
  - pyqt
  - spyder
  - jupyter
  - urllib3
  - werkzeug
  - xlrd
  - xlsxwriter
  - xlutils
  - pip:
    - dash
    - dash-daq
    - flake8
    - gaitutils
    - pytest

