name: gaitutils
channels:
  - conda-forge
dependencies:
  - btk
  - configobj
  - flake8
  - flask
  - freetype
  - matplotlib
  - numpy
  - scipy
  - python
  - openpyxl
  - pip
  - plotly
  - pyqt
  - spyder
  - psutil
  - jupyter
  - urllib3
  - werkzeug
  - xlrd
  - xlsxwriter
  - xlutils
  - pyedflib
  - pip:
    - dash
    - kaleido
    - dash-daq
    - pytest
    - https://github.com/jjnurminen/gaitutils/archive/master.zip
    - https://github.com/jjnurminen/ulstools/archive/master.zip
    - https://github.com/jjnurminen/configdot/archive/master.zip

