version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  win: circleci/windows@2.2.0

workflows:
  test:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test

jobs:
  build-and-test:  # This is the name of the job, feel free to change it to better match what you're trying to do!
    executor:
      name: win/default
      shell: bash
    steps:
      - checkout
      
      - run:
          name: install deps
          command: |
            conda env create -f environment.yml
      
      - run:
          name: run tests
          command: |
            source activate gaitutils
            pytest tests/
   
